/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mvbos.mymer;

import br.com.mvbos.jeg.element.ElementModel;
import br.com.mvbos.mymer.el.TableElement;
import br.com.mvbos.mymer.xml.XMLUtil;
import br.com.mvbos.mymer.xml.field.View;
import br.com.mvbos.mymer.xml.field.ViewTable;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author MarcusS
 */
public class NewViewWindow extends javax.swing.JFrame {

    private int px;
    private short ct;

    private View selected;
    private List<View> views;
    private ElementModel[] selectedTables = new ElementModel[0];

    public ElementModel[] getSelectedTables() {
        return selectedTables;
    }

    public void setSelectedTables(ElementModel[] selectedTables) {
        this.selectedTables = selectedTables;
        temp.delete(0, temp.length());

        for (ct = 0; ct < selectedTables.length; ct++) {
            if (selectedTables[ct] == null) {
                break;
            }

            temp.append(selectedTables[ct].getName()).append(", ");
        }

        setTitle(temp.toString());
        lblInfo.setText(String.format("%d tables selecteds.", ct));
    }

    /**
     * Creates new form NewViewWindow
     */
    public NewViewWindow() {
        initComponents();

        DefaultListModel<String> def = (DefaultListModel<String>) lstViews.getModel();
        views = XMLUtil.loadViews();
        if (views != null) {
            for (View v : views) {
                def.addElement(v.getName());
            }

        } else {
            views = new ArrayList<>(5);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        btnNext = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstViews = new javax.swing.JList();
        tfLabelTables = new javax.swing.JTextField();
        lblInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl.setText("Name:");

        tfName.setText("New View");

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        lstViews.setModel(new DefaultListModel<String>());
        lstViews.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstViews.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstViewsValueChanged(evt);
            }
        });
        lstViews.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lstViewsKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(lstViews);

        tfLabelTables.setEditable(false);

        lblInfo.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfName))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNext))
                    .addComponent(tfLabelTables))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfLabelTables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInfo)
                    .addComponent(btnNext))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed

        ViewWindow vw = new ViewWindow();

        if (selected == null && ct == 0) {
            tfLabelTables.setText("No tables selected.");

        } else if (selected == null) {

            selected = new View(tfName.getText());
            //List<TableElement> lst = new ArrayList<>(selectedTables.length);

            for (ElementModel e : selectedTables) {
                if (e instanceof TableElement) {
                    TableElement t = (TableElement) e;

                    //lst.add(t);
                    ViewTable v = new ViewTable(t.getDataBase().getName(), t.getName());

                    vw.addTable(copy(t, v));
                    selected.getTables().add(v);
                }
            }

            views.add(selected);

        } else {
            selected.setName(tfName.getText());

            for (ViewTable v : selected.getTables()) {

                TableElement t = XMLUtil.findByName(v.getDataBaseName(), v.getTableName());

                if (t == null) {
                    Logger.getLogger(NewViewWindow.class.getName()).log(Level.INFO, "erro to find {0} {1}", new String[]{v.getDataBaseName(), v.getTableName()});
                    continue;
                }

                vw.addTable(copy(t, v));

                if (!selected.getTables().contains(v)) {
                    selected.getTables().add(new ViewTable(t.getDataBase().getName(), t.getName()));
                }
            }

            for (ElementModel e : selectedTables) {
                if (e instanceof TableElement) {
                    TableElement t = (TableElement) e;

                    ViewTable v = new ViewTable(t.getDataBase().getName(), t.getName());

                    if (!selected.getTables().contains(v)) {
                        vw.addTable(copy(t, v));
                        selected.getTables().add(v);
                    }
                }
            }
        }

        vw.init(selected, views);
        vw.setVisible(true);

        this.dispose();

    }//GEN-LAST:event_btnNextActionPerformed

    private final StringBuilder temp = new StringBuilder(100);

    private void lstViewsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstViewsValueChanged

        if (evt.getValueIsAdjusting()) {
            temp.delete(0, temp.length());

            selected = views.get(lstViews.getSelectedIndex());
            tfName.setText(selected.getName());

            for (ViewTable v : selected.getTables()) {
                temp.append(v.getTableName()).append(", ");
            }

            tfLabelTables.setText(temp.toString());
        }

    }//GEN-LAST:event_lstViewsValueChanged

    private void lstViewsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lstViewsKeyReleased

        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            int idx = lstViews.getSelectedIndex();
            if (idx > -1) {
                views.remove(idx);
                ((DefaultListModel) lstViews.getModel()).removeElementAt(idx);

                selected = null;
                tfLabelTables.setText(null);
            }
        }

    }//GEN-LAST:event_lstViewsKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JList lstViews;
    private javax.swing.JTextField tfLabelTables;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables

    private TableElement copy(TableElement t, ViewTable v) {
        int ppx = v.getPx() == 0 ? px : v.getPx();

        TableElement copy = new TableElement(ppx, v.getPy(), t.getWidth(), t.getHeight(), t.getDataBase(), t.getName());
        copy.setFields(t.getFields());
        copy.update();

        px += copy.getWidth() + 10;

        return copy;
    }
}
