/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mvbos.mymer.sync;

import br.com.mvbos.mymer.el.DataBaseElement;
import br.com.mvbos.mymer.el.TableElement;
import br.com.mvbos.mymer.entity.DataBaseEntity;
import br.com.mvbos.mymer.entity.EntityManager;
import br.com.mvbos.mymer.entity.EntityUtil;
import br.com.mvbos.mymer.util.FileUtil;
import br.com.mvbos.mymer.xml.DataBaseStore;
import br.com.mvbos.mymer.xml.field.DataBase;
import br.com.mvbos.mymer.xml.field.Table;
import java.io.File;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author marcuss
 */
public class DiffExportWindow extends javax.swing.JFrame {

    /**
     * Creates new form DiffExportWindow
     */
    public DiffExportWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeGroup = new javax.swing.ButtonGroup();
        fileChooser = new javax.swing.JFileChooser();
        rQuick = new javax.swing.JRadioButton();
        rFull = new javax.swing.JRadioButton();
        btn = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        fileChooser.setCurrentDirectory(null);
        fileChooser.setDialogTitle("Select output directory");
        fileChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Differ export");
        setResizable(false);

        typeGroup.add(rQuick);
        rQuick.setSelected(true);
        rQuick.setText("Quick export");

        typeGroup.add(rFull);
        rFull.setText("Full export");

        btn.setText("Export to ...");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        lblInfo.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rQuick, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rFull, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rQuick)
                    .addComponent(rFull)
                    .addComponent(btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        int showSaveDialog = fileChooser.showOpenDialog(this);
        if (showSaveDialog == JFileChooser.APPROVE_OPTION) {
            progressBar.setValue(0);
            new Thread() {

                @Override
                public void run() {
                    try {
                        File dir = fileChooser.getSelectedFile();
                        lblInfo.setText(dir.getAbsolutePath());

                        final EntityManager em = EntityManager.e();

                        final StringBuilder sb = new StringBuilder();

                        final List<DataBaseElement> localBases = em.getEntity(DataBaseEntity.class).getList();

                        float percent = 100f / localBases.size();

                        DataBaseStore dbs = FileUtil.open();

                        for (DataBaseElement localBase : localBases) {
                            DataBase remote = EntityUtil.findBaseByName(dbs, localBase.getName());

                            if (remote == null) {
                                Differ.addBase(localBase, sb);
                                for(TableElement t : localBase.getTables()){
                                    Differ.addTable(t, sb);
                                }
                                
                            } else {

                                //float pp = percent / d.getTables().size();
                                for (TableElement t : localBase.getTables()) {
                                    Table remoteTable = EntityUtil.findTableByName(remote, t.getName());

                                    if (remoteTable == null) {
                                        Differ.addTable(t, sb);
                                    } else {
                                        sb.append(Differ.compare(t, remoteTable));
                                    }

                                    //pp += pp;
                                    //progressBar.setValue(progressBar.getValue() + Math.round(pp));
                                }

                                for (Table t : remote.getTables()) {
                                    TableElement temp = EntityUtil.findTableByName(localBase, t.getName());
                                    if (temp == null) {
                                        temp = new TableElement(localBase, t);
                                        Differ.removeTable(temp, sb);
                                    }
                                }
                            }

                            if (sb.length() > 0 || rFull.isSelected()) {
                                FileUtil.write(dir.getAbsolutePath(), localBase.getName().concat(".htm"), sb);
                                sb.delete(0, sb.length());
                            }

                            progressBar.setValue(progressBar.getValue() + Math.round(percent));
                        }

                    } catch (Exception e) {
                        Logger.getLogger(DiffExportWindow.class.getName()).log(Level.WARNING, e.getMessage());
                    }
                }

            }.start();
        }

    }//GEN-LAST:event_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JRadioButton rFull;
    private javax.swing.JRadioButton rQuick;
    private javax.swing.ButtonGroup typeGroup;
    // End of variables declaration//GEN-END:variables
}
